server:
    port: 8888
spring:
  application:
    name: ms-gateway
  cloud:
    config:
        enabled: false
    discovery:
        enabled: true
#    gateway:
#      routes:
#        - id: catalogue-service
#          uri: http://localhost:8080
#          predicates:
#            - Path= /catalogue/**
#        - id: security-service
#          uri: http://localhost:8089
#          predicates:
#            - Path= /auth/**
#        - id: customer-service
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customer/**
#        - id: order-service
#          uri: http://localhost:8082
#          predicates:
#            - Path= /order/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
