server:
    port: 8888
spring:
  application:
    name: ms-gateway
  cloud:
    config:
        enabled: false
    discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
